-- Created by Victoria Lane
-- Created on March 11, 2024
-- Purpose: example seed data for resources table

INSERT INTO resources (name, url, description, owner_id, category_id, resource_type_id, date_added)
VALUES
('Butter Chicken Recipe', 'https://www.indianhealthyrecipes.com/butter-chicken/', 'The ultimate comfort food! Make the best flavour-packed, creamy, delicious authentic Indian Butter Chicken at home with this easy recipe.' , 4, 1, 11, '2024-02-14 03:27:05'),
('Business Plan Template', 'https://www.score.org/resource/business-plan-template-startup-business', 'Create a solid business plan with this template designed for startup businesses.', 7, 1, 9, '2024-01-15 09:45:21'),
('Introduction to Computer Science', 'https://www.coursera.org/learn/cs101', 'Get started with the basics of computer science through this introductory course on Coursera.', 3, 2, 9, '2024-01-28 14:12:34'),
('Yoga for Beginners', 'https://www.yogabasics.com/', 'Embark on a journey to health and wellness with beginner-friendly yoga practices.', 8, 3, 9, '2024-02-05 18:56:47'),
('Creative Writing Workshop', 'https://writers.com/', 'Unleash your creativity and improve your writing skills with online workshops from Writers.com.', 5, 4, 9, '2024-02-01 12:30:15'),
('Learn French Basics', 'https://www.duolingo.com/course/fr/en/Learn-French', 'Start your language-learning journey with Duolingo and master the basics of the French language.', 2, 5, 9, '2024-02-22 07:22:59'),
('Introduction to Physics', 'https://www.khanacademy.org/science/physics', 'Explore the fundamental concepts of physics through engaging videos and exercises on Khan Academy.', 6, 6, 3, '2024-01-10 16:45:38'),
('Positive Thinking Guide', 'https://www.psychologytoday.com/us/basics/positive-psychology', 'Learn the principles of positive thinking and boost your mental well-being with Psychology Today.', 9, 7, 8, '2024-02-15 21:09:47'),
('World History Timeline', 'https://www.history.com/topics/world-history', 'Dive into world history with a comprehensive timeline and articles from the History Channel.', 1, 8, 8, '2024-02-29 08:37:12'),
('Introduction to Calculus', 'https://www.khanacademy.org/math/calculus-1', 'Master the basics of calculus with clear explanations and practice problems on Khan Academy.', 10, 9, 3, '2024-01-02 14:56:23'),
('Environmental Sustainability Guide', 'https://www.epa.gov/sustainability', 'Learn about environmental sustainability and discover ways to make a positive impact with the EPA.', 4, 10, 5, '2024-02-19 10:18:45'),
('Classic Italian Recipes', 'https://www.foodnetwork.com/recipes/photos/classic-italian-recipes', 'Indulge in the flavors of Italy with a collection of classic Italian recipes from Food Network.', 11, 11, 1, '2024-01-14 03:27:05'),
('Introduction to Music Theory', 'https://www.musictheory.net/lessons', 'Explore the fundamentals of music theory with interactive lessons and exercises on MusicTheory.net.', 12, 12, 9, '2024-02-11 09:45:21'),
('Great Literary Works', 'https://www.goodreads.com/list/show/1.Best_Books_Ever', 'Discover a treasure trove of great literary works with this list from Goodreads.', 13, 13, 12, '2024-02-28 14:12:34'),
('Architectural Design Principles', 'https://www.archdaily.com/801849/a-beginners-guide-to-starting-your-architecture-portfolio', 'Learn the principles of architectural design and kickstart your architecture portfolio with ArchDaily.', 14, 14, 9, '2024-02-18 18:56:47'),
('Outdoor Fitness Workouts', 'https://www.shape.com/fitness/cardio/outdoor-fitness-workouts', 'Stay fit and active with a variety of outdoor fitness workouts from Shape Magazine.', 15, 15, 9, '2024-01-05 12:30:15'),
('Miscellaneous Knowledge Repository', 'https://www.wikipedia.org/', 'Explore a wide range of topics in this miscellaneous knowledge repository on Wikipedia.', 16, 16, 13, '2024-02-02 07:22:59'),
('Digital Marketing Strategies', 'https://www.digitalmarketer.com/', 'Explore effective digital marketing strategies and stay ahead in the online landscape.', 12, 1, 7, '2024-02-10 11:30:45'),
('Python Programming Basics', 'https://www.learnpython.org/', 'Learn the basics of Python programming with interactive tutorials and exercises.', 18, 2, 9, '2024-01-20 14:45:23'),
('Meditation for Stress Relief', 'https://www.headspace.com/', 'Discover guided meditations to relieve stress and promote mindfulness with Headspace.', 9, 3, 2, '2024-02-28 09:15:34'),
('Digital Photography Tips', 'https://digital-photography-school.com/', 'Improve your digital photography skills with tips and tutorials from Digital Photography School.', 14, 4, 1, '2024-01-15 17:40:56'),
('Spanish Language Learning Course', 'https://www.rosettastone.com/', 'Embark on a language-learning journey with Rosetta Stone to master Spanish.', 6, 5, 11, '2024-02-05 08:22:17'),
('Chemistry Basics', 'https://www.khanacademy.org/science/chemistry', 'Understand the fundamentals of chemistry through engaging lessons on Khan Academy.', 20, 6, 3, '2024-01-10 13:55:48'),
('Mindfulness Practices', 'https://www.mindful.org/', 'Incorporate mindfulness practices into your daily life for improved well-being.', 3, 7, 4, '2024-02-15 20:10:32'),
('Ancient Civilizations History', 'https://www.history.com/topics/ancient-history', 'Explore the history of ancient civilizations and their contributions to humanity.', 5, 8, 8, '2024-02-29 16:23:09'),
('Statistics for Data Analysis', 'https://www.khanacademy.org/math/statistics-probability', 'Enhance your data analysis skills with statistical concepts on Khan Academy.', 17, 9, 5, '2024-01-02 10:38:57'),
('Ecology and Conservation', 'https://www.worldwildlife.org/', 'Learn about ecology and conservation efforts to protect our planet''s biodiversity.', 22, 10, 6, '2024-02-19 14:20:37'),
('Italian Pasta Recipes', 'https://www.allrecipes.com/recipes/205/main-dish/pasta/', 'Discover a variety of delicious Italian pasta recipes to try at home.', 10, 11, 1, '2024-01-14 08:30:12'),
('Guitar Basics', 'https://www.justinguitar.com/', 'Start your guitar-playing journey with beginner-friendly lessons from JustinGuitar.', 19, 12, 2, '2024-02-11 12:55:21'),
('Classic Literature Collection', 'https://www.gutenberg.org/', 'Access a vast collection of classic literature for free on Project Gutenberg.', 8, 13, 9, '2024-02-28 18:40:44'),
('Architectural Sketching Techniques', 'https://www.archdaily.com/804664/15-tips-for-effective-architectural-sketching', 'Explore effective sketching techniques for architectural design.', 15, 14, 9, '2024-02-18 09:10:57'),
('Outdoor Yoga Workouts', 'https://www.yogajournal.com/', 'Combine the benefits of yoga with the outdoors through these guided workouts.', 13, 15, 2, '2024-01-05 15:25:30'),
('Philosophy Explained', 'https://plato.stanford.edu/', 'Delve into the world of philosophy with comprehensive explanations on Stanford Encyclopedia of Philosophy.', 11, 16, 13, '2024-02-02 11:15:24'),
('Digital Art Resources', 'https://www.deviantart.com/resources/', 'Access a variety of digital art resources, including brushes, textures, and tutorials.', 7, 16, 7, '2024-02-20 06:45:18'),
('Business Negotiation Skills', 'https://www.pon.harvard.edu/', 'Enhance your business negotiation skills with resources from the Program on Negotiation at Harvard Law School.', 16, 1, 9, '2024-01-12 14:30:42'),
('Web Development Fundamentals', 'https://developer.mozilla.org/en-US/docs/Learn', 'Master the fundamentals of web development with Mozilla Developer Network (MDN) resources.', 21, 2, 9, '2024-02-25 09:52:36'),
('Guided Sleep Meditations', 'https://www.calm.com/', 'Improve your sleep with guided meditations and relaxation techniques from Calm.', 4, 3, 2, '2024-01-18 22:10:53'),
('Photography Composition Techniques', 'https://digital-photography-school.com/composition-tips-for-your-photography/', 'Enhance your photography with composition tips and techniques.', 2, 4, 1, '2024-02-15 17:58:10'),
('Japanese Language Learning Resources', 'https://www.tofugu.com/', 'Explore resources for learning Japanese, including language guides and cultural insights.', 1, 5, 11, '2024-02-08 13:40:29'),
('Physics Experiments at Home', 'https://www.exploratorium.edu/snacks', 'Engage in physics experiments at home with simple and fun activities from Exploratorium.', 18, 6, 4, '2024-01-03 19:30:15'),
('Confidence Building Techniques', 'https://www.psychologytoday.com/us/basics/confidence', 'Learn techniques to build and boost your confidence with Psychology Today.', 20, 7, 2, '2024-02-20 08:45:37'),
('Ancient Greek History', 'https://www.history.com/topics/ancient-greece', 'Explore the history of Ancient Greece and its impact on civilization.', 9, 8, 8, '2024-02-29 11:16:24'),
('Data Visualization with Python', 'https://matplotlib.org/', 'Explore data visualization techniques using Python with Matplotlib documentation.', 7, 9, 3, '2024-01-06 14:55:42'),
('Green Living Tips', 'https://www.nrdc.org/stories/10-ways-live-more-sustainably', 'Discover practical tips for green living and sustainability from NRDC.', 14, 10, 5, '2024-02-24 10:20:59'),
('Chemical Reactions at Home', 'https://www.scientificamerican.com/article/four-safe-chemistry-experiments-for-the-holidays/', 'Perform safe and simple chemical reactions at home with Scientific American.', 16, 6, 4, '2024-01-03 19:30:15'),
('Public Speaking Confidence', 'https://www.toastmasters.org/', 'Build confidence in public speaking with resources and tips from Toastmasters.', 6, 7, 13, '2024-02-20 08:45:37'),
('Roman History Overview', 'https://www.history.com/topics/ancient-rome', 'Explore an overview of Roman history and its impact on civilization.', 18, 8, 8, '2024-02-29 11:16:24'),
('Data Analysis with Pandas', 'https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html', 'Learn data analysis with Pandas through the official documentation and tutorials.', 10, 9, 3, '2024-01-06 14:55:42'),
('Sustainable Living Tips', 'https://www.greenpeace.org/usa/sustainable-living/', 'Discover tips for sustainable living and reducing your environmental impact with Greenpeace.', 5, 10, 5, '2024-02-24 10:20:59'),
('French Pastry Recipes', 'https://www.bonappetit.com/recipes/desserts/slideshow/french-pastry-dessert-recipes', 'Indulge in the art of French pastry with these delightful recipes from Bon Appétit.', 11, 11, 1, '2024-01-14 08:30:12');
